config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  
  get 'about' => 'welcome#about'

  resources :registered_applications, except: [:index]
  
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      match '/events', to: 'events#preflight', via: [:options]
      resources :events, only: [:create]
    end
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :application
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications  
end

app/controllers/api/v1/events_controller.rb
class API::V1::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers
  
  def create
    @application = Application.find_by(url: request.env['HTTP_ORIGIN'])
        
    if @application.nil?
      render json: "Unregistered Application", status: :unprocessable_entity
    else
      @event = @application.events.new(event_params)
      if @event.save!
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    end
  end
  
  def preflight
    head 200
  end
  
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end
  
  private
  def event_params
    params.permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!

  def show
    @application = Application.find(params[:id])
    @events = @application.events.group_by(&:name)
  end

  def new
    @user = current_user
    @application = @user.applications.new
  end

  def create
    @user = current_user
    @application = @user.applications.new
    @application.name = params[:application][:name]
    @application.url = params[:application][:url]

    if @application.save
      flash[:notice] = "Success! Now listening for events from " + @application.url
      redirect_to registered_application_path(@application.id)
    else
      flash.now[:alert] = "There was an error saving the new site. Please try again."
      render :new
    end
  end

  def edit
    @application = Application.find(params[:id])
  end

  def update
    @application = Application.find(params[:id])
    @application.name = params[:application][:name]
    @application.url = params[:application][:url]

    if @application.save
      flash[:notice] = "\""+@application.name+"\" saved successfully!"
      redirect_to registered_application_path(@application.id)
    else
      flash.now[:alert] = "There was an error saving the new site. Please try again."
      render :edit
    end
  end

  def destroy
    @application = Application.find(params[:id])

    if @application.destroy
      flash[:notice] = "\"#{@application.name}\" was deleted successfully."
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error deleting the site."
      render :show
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metrics | API-Driven Analytics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'images/favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("logo-blocmetrics.png") + "Metrics", root_path, class: "navbar-brand" %>
          </div>
      
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="<%= root_path %>">Home<span class="sr-only">(current)</span></a></li>
              <li><a href="<%= about_path %>">About</a></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <p class="navbar-text">Welcome, 
                  <%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link userHighlight' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </p>
              <% else %>
                <p class="navbar-text">
                  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> &bull;
                  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
                </p>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
  
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash.now[:alert] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% elsif flash.now[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
  
      <%= yield %>

    </div>
    
    <footer>
      <div class="container">
        <h4 class="text-muted" align="center">An API Tracking Service and Reporting Tool &bull; <%= Time.now.year %></h4>
      </div>
    </footer>
  </body>
</html>

app/views/registered_applications/edit.html.erb
<h1>Edit this site:</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @application, :url => registered_application_path(@application) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter site name" %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter site URL" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="page-header col-md-12">
  <h1>Track a New Site:</h1>
</div>

<div class="col-md-10">
  <%= form_for @application, :url => registered_applications_path(@application) do |f| %>
    <div class="form-group">
      <%= f.label :name, id: "app-name" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter a site title" %>
    </div>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: "form-control", placeholder: "Enter the site URL" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save New Site", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/registered_applications/show.html.erb
<div class="pageheader">
  <div class="col-md-8">
    <h2><%= @application.name %> <small class="text-muted"><%= @application.url%></small></h2>
  </div>
  <div style="margin-top: 20px;" class="col-md-4">
    <%= link_to "Delete", registered_application_path(@application), method: :delete, class: 'btn btn-danger pull-right', data: {confirm: 'Are you sure you want to delete this site?'} %>
    <%= link_to "Edit Site", edit_registered_application_path(@application), class: 'btn btn-success pull-right' %>
  </div>
</div>

<div class="col-md-12 tracked-apps">
  <h3>Tracked Events:</h3>
  <h5>Currently tracking <%= @events.count %> events</h5>
  <div class="media">
    <div class="media-body">
      <%= pie_chart @application.events.group(:name).count %>
    </div>
  </div>
</div>

<div class="page-header col-md-12">
  <h3>Start Tracking New Events!</h3>
  <pre>
    var blocmetrics = {};
    blocmetrics.report = function(eventName){
    var event = { name: eventName };
    var request = new XMLHttpRequest();
    
    request.open("POST", "https://blocmetrics-by-drianhillman.herokuapp.com/api/v1/events", true);
    request.setRequestHeader('Content-Type', 'application/json');
    request.send(JSON.stringify(event));
    };
    
    blocmetrics.report("MY EVENT TITLE");
  </pre>
  <p class="lead">Copy this snippet! Add this as JavaScript to either your site header or a specific page, to begin tracking events. Be sure to change <code> MY EVENT TITLE</code> to the label of your choice. 🚀</p>
</div>

app/views/welcome/about.html.erb
<div class="page-header">
  <h1>About</h1>
</div>
  
<div class="col-md-12">
  <blockquote>
    <p>Blocmetrics is an analytics service and reporting tool that you can use with your web apps to track user activity and report results.</p>
  </blockquote>

  <h4>Blocmetrics consists of&mdash;</h4>
  <ul>
    <li>A client-side JavaScript snippet that allows a user to track events on their website.</li>
    <li>A server-side API that captures and saves those events to a database.</li>
    <li>A Rails application (you are here) that displays the captured event data for a user.</li>
  </ul>
</div>

<div class="col-md-12">
  <h2>Feature set:</h2>
  <ol>
    <li>As a user, I want to securely <strong>sign up</strong> for a free account by providing a name, password, and email. I also want to <strong>sign in and out</strong> of Blocmetrics.</li>
    <li>As a user, I want to <strong>register</strong> an application with Blocmetrics for tracking</li>
    <li>As a user, I want <strong>events association</strong> with registered applications</li>
    <li>As a developer, I want to receive incoming events openly via an <strong>API</strong> controller</li>
    <li>As a user, I want to <strong>use JavaScript</strong> to capture client-side events in my application</li>
    <li>As a user, I want to <strong>see a graph of events</strong> for each registered application</li>
  </ol>
</div>

<div class="col-md-12">
  <h2>Created By:</h2>
  <p>Blocmetrics is handcrafted by <a href="http://drianhillman.me/" target="_blank">Drian Hillman</a> through the Software Engineering Track at <a href="https://www.bloc.io">BLOC</a>.</p>
</div>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>Your Tracked Sites:</h1>
</div>

<div class="col-md-10 sites-list">
    <% @user.applications.each do |app| %>
    <div class="media">
      <div class="media-body">
        <h3 class="media-heading">
          <%= link_to app.name, registered_application_path(app) %> <small><%= app.url %></small>
        </h3>
      </div>
    </div>
    <% end %>
</div>

<% if current_user %>
  <div class="col-md-2">
    <%= link_to "+Add New Site", new_registered_application_path(@application), class: 'btn btn-success pull-right' %>
  </div>
<% end %>